services:
  food-app:
    image: ghcr.io/kroonk/kiidea:latest
    pull_policy: always
    container_name: kiidea-food-app
    ports:
      - "3000:3000"
    volumes:
      # Persistentes Volume: Nutzerdaten (DB) überleben Container-Updates
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
    restart: unless-stopped
    networks:
      - npm-net

networks:
  npm-net:
    external: true
